### ISSUE TITLE
Article View

### ISSUE THREAD

**Issue by chadturnbull** [northlandchurch/Website-Styles#8]
The individual articles need to be over a white background. We can have the header image be in the hero location if that is the best application for the main image (I defer to you on that one), but then the article title, subtitle, author, and text need to be over white and be in a more narrow, typical news/blog reading width.

It's currently this:
![screen shot 2015-07-16 at 1 45 16 pm](https://cloud.githubusercontent.com/assets/10187666/8730858/8aacd86c-2bc1-11e5-9ccf-c3f12f45ac90.png)

Keeping the header image as a hero image, I see it being more akin to this (I reduced the size so that more of the format would show):
![screen shot 2015-07-16 at 1 50 54 pm](https://cloud.githubusercontent.com/assets/10187666/8730895/c6f76184-2bc1-11e5-810a-02ec5b500a81.png)

Additionally, Ice Mountains on Pluto? Craziness.

**Comment by jhnwlsn** [comment]
We can come back to this. The design you are seeing here is simply placeholder as I'll be getting to it soon.

With that said, the background is dark around the actual article being white so that it matches the resources page. This helps that whole section of the site tie in together and feel more like a magazine.

Anyway, I'm going to close this issue for now, and once I get that design a little more built out from what I was envisioning, I'll reopen this issue.
